// Auth user types

export const AUTH_USER = 'AUTH_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

// Login user types

export const LOGIN_USER_INPUT_CHANGE = 'LOGIN_USER_INPUT_CHANGE';
export const LOGIN_USER_FORM_SUCCESS = 'LOGIN_USER_FORM_SUCCESS';
export const LOGIN_USER_FORM_ERROR = 'LOGIN_USER_FORM_ERROR';
export const LOGIN_USER_FORM_LOADING = 'LOGIN_USER_FORM_LOADING';

// Register user types

export const REGISTER_USER_INPUT_CHANGE = 'REGISTER_USER_INPUT_CHANGE';
export const REGISTER_USER_FORM_SUCCESS = 'REGISTER_USER_FORM_SUCCESS';
export const REGISTER_USER_FORM_ERROR = 'REGISTER_USER_FORM_ERROR';
export const REGISTER_USER_FORM_LOADING = 'REGISTER_USER_FORM_LOADING';

// Update user types

export const UPDATE_USER_INPUT_CHANGE = 'UPDATE_USER_INPUT_CHANGE';
export const UPDATE_USER_FORM_SUCCESS = 'UPDATE_USER_FORM_SUCCESS';
export const UPDATE_USER_FORM_ERROR = 'UPDATE_USER_FORM_ERROR';
export const UPDATE_USER_FORM_LOADING = 'UPDATE_USER_FORM_LOADING';

// Get users types

export const GET_USERS_LIST = 'GET_USERS_LIST';

// Get products types

export const GET_PRODUCTS_LIST = 'GET_PRODUCTS_LIST';

// Add product types

export const ADD_PRODUCT_INPUT_CHANGE = 'ADD_PRODUCT_INPUT_CHANGE';
export const ADD_PRODUCT_FORM_LOADING = 'ADD_PRODUCT_FORM_LOADING';
export const ADD_PRODUCT_FORM_ERROR = 'ADD_PRODUCT_FORM_ERROR';
export const ADD_PRODUCT_FORM_SUCCESS = 'ADD_PRODUCT_FORM_SUCCESS';

// Add product types

export const EDIT_PRODUCT_INPUT_CHANGE = 'EDIT_PRODUCT_INPUT_CHANGE';
export const EDIT_PRODUCT_FORM_LOADING = 'EDIT_PRODUCT_FORM_LOADING';
export const EDIT_PRODUCT_FORM_ERROR = 'EDIT_PRODUCT_FORM_ERROR';
export const EDIT_PRODUCT_FORM_SUCCESS = 'EDIT_PRODUCT_FORM_SUCCESS';
export const SET_PRODUCT_ID_ON_EDIT = 'SET_PRODUCT_ID_ON_EDIT';
